### ISSUE TITLE
Clean up and commit

### ISSUE THREAD

**Issue by marek-saji** [marek-saji/mplay.sh#1]
- [ ] commit current version
- [ ] clean up removing all cruft
- [ ] change versioning schema to semver (new version will be 5.0)
# Roadmap
## 5.0
- pause music before playing, resume after
- resolve media urls with youtube-dl (where available)
- play magnet links using peerfix (where available)
- lookup titles after watching on filmweb for marking as watched and rating
## 5.1
- use trakt.tv API to mark as „currently watching” and later as watched (notify about success/failure)
- configure lookup service (filmweb, imdb, trakt, …). allow two kinds depending on length (series vs movies)
